/**
 * (c) Copyright IBM Corporation 2017.
 * This is licensed under the following license.
 * The Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
 * U.S. Government Users Restricted Rights:  Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 */

import groovy.util.XmlSlurper

plugins {
    id "org.jenkins-ci.jpi" version "0.49.0"
}

group = "com.urbancode.ds.jenkins.plugins"
version = getVersion()
description = "Publish artifacts into an IBM UrbanCode Deploy component as a build step."

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType(JavaCompile) {
    options.release = 8
}

jenkinsPlugin {
    coreVersion = "2.164.3"                                         // Minimum Jenkins core version
    displayName = "IBM UrbanCode Deploy Jenkins Pipeline Plugin"    // Human-readable name of plugin
    url = "https://developer.ibm.com/urbancode/plugin/jenkins-2-0/"
    gitHubUrl = "https://github.com/IBM-UrbanCode"
    shortName = "ibm-ucdeploy-build-steps"

    developers {
        developer {
            id = "nhmathis"
            name = "Nicholas Mathison"
            email = "nhmathis(at)us(dot)ibm(dot)com"
        }
        developer {
            id = "jrbarto"
            name = "Jeffrey Barto"
            email = "jrbarto(at)us(dot)ibm(dot)com"
        }
    }
}

repositories {
    mavenCentral()
    maven {
        url "https://repo.jenkins-ci.org/public/"
    }
    maven {
        url "https://public.dhe.ibm.com/software/products/UrbanCode/maven2/"
    }
}

dependencies {
    implementation 'com.ibm.urbancode.commons:uDeployRestClient:+'
    implementation 'javax.ws.rs:jsr311-api:1.1.1'
}

def getVersion() {
    def pomFile = new XmlSlurper().parseText(new File("pom.xml").text)
    def version = pomFile.version.text()
    return version.replace('${env.buildLife}', "open")
}
