/**
 * (c) Copyright IBM Corporation 2017.
 * This is licensed under the following license.
 * The Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
 * U.S. Government Users Restricted Rights:  Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 */
import groovy.xml.XmlSlurper
buildscript {
    repositories {
        maven {
            url "https://repo.jenkins-ci.org/public/"
        }
    }
}
plugins {
  id "org.jenkins-ci.jpi" version "0.43.0"
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs << '-Xlint:-options'
}

group = "com.urbancode.ds.jenkins.plugins"
version = getVersion()
description = "Publish artifacts into an IBM UrbanCode Deploy component as a build step."

jenkinsPlugin {
    coreVersion = "1.587"                                      // Version of Jenkins core this plugin depends on.
    displayName = "IBM UrbanCode Deploy Jenkins Pipeline Plugin" // Human-readable name of plugin.
    url = "https://developer.ibm.com/urbancode/plugin/jenkins-2-0/" // URL for plugin on Jenkins wiki or elsewhere.
    gitHubUrl = "https://github.com/IBM-UrbanCode"                // Plugin URL on GitHub. Optional.
    shortName = "ibm-ucdeploy-pipeline-open"                     // Plugin ID, defaults to the project name without trailing '-plugin'

    // The developers section is optional, and corresponds to the POM developers section.
    developers {[
        developer {
            id "nhmathis"
            name "Nicholas Mathison"
            email "nhmathis(at)us(dot)ibm(dot)com"
        },
        developer {
            id "jrbarto"
            name "Jeffrey Barto"
            email "jrbarto(at)us(dot)ibm(dot)com"
        }
    ]}
}

repositories {
    mavenCentral()
    maven {
        url "https://public.dhe.ibm.com/software/products/UrbanCode/maven2/"
    }
}

dependencies {
    implementation 'org.slf4j:slf4j-api:1.7.36'
    implementation 'com.ibm.urbancode.commons:uDeployRestClient:+'
    // implementation 'com.ibm.urbancode.commons:CommonsFileUtils:+'
    // implementation 'com.ibm.urbancode.commons:HttpComponents-Util:+'
    // implementation 'com.ibm.urbancode.commons:CommonsUtil:+'
    // implementation 'com.sun.jersey:jersey-core:1.12'
    // implementation 'com.sun.jersey:jersey-client:1.12'
    implementation 'javax.ws.rs:jsr311-api:1.1.1'
    // implementation 'org.codehaus.jettison:jettison:1.1'
    // implementation 'commons-lang:commons-lang:2.5'
    // implementation group: 'org.apache.httpcomponents', name: 'httpclient', version: '4.3.4'
    // implementation group: 'org.apache.httpcomponents', name: 'httpcore', version: '4.3.4'
    // implementation group: 'org.apache.httpcomponents', name: 'httpmime', version: '4.3.4'
}

def static getVersion() {
    def pomFile = new XmlSlurper().parseText(new File("pom.xml").text)
    def version = pomFile.version.text()
    return version.replace('${env.buildLife}', "open")
}
